#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Nov 30 19:46:30 -03 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_fir_filter_behav -key {Behavioral:sim_1:Functional:tb_fir_filter} -tclbatch tb_fir_filter.tcl -view /home/marcos/Repositorios/pds-MSE-8Co2023/tb_fir_filter_behav.wcfg -log simulate.log"
xsim tb_fir_filter_behav -key {Behavioral:sim_1:Functional:tb_fir_filter} -tclbatch tb_fir_filter.tcl -view /home/marcos/Repositorios/pds-MSE-8Co2023/tb_fir_filter_behav.wcfg -log simulate.log

