# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/PersonalCloud/MSE/PDS/TP_Final/pds-MSE-8Co2023/PDS_Test.srcs/sources_1/ip/cordic_0/cordic_0.xci
# IP: The module: 'cordic_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PersonalCloud/MSE/PDS/TP_Final/pds-MSE-8Co2023/PDS_Test.gen/sources_1/ip/cordic_0/cordic_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/PersonalCloud/MSE/PDS/TP_Final/pds-MSE-8Co2023/PDS_Test.srcs/sources_1/ip/cordic_0/cordic_0.xci
# IP: The module: 'cordic_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PersonalCloud/MSE/PDS/TP_Final/pds-MSE-8Co2023/PDS_Test.gen/sources_1/ip/cordic_0/cordic_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
